# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import addressValidation_pb2 as addressValidation__pb2


class ValidateAddressServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateAddress = channel.unary_unary(
                '/ValidateAddressService/ValidateAddress',
                request_serializer=addressValidation__pb2.ValidateAddress_Request.SerializeToString,
                response_deserializer=addressValidation__pb2.ValidateAddress_Response.FromString,
                )


class ValidateAddressServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidateAddressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAddress,
                    request_deserializer=addressValidation__pb2.ValidateAddress_Request.FromString,
                    response_serializer=addressValidation__pb2.ValidateAddress_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ValidateAddressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidateAddressService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ValidateAddressService/ValidateAddress',
            addressValidation__pb2.ValidateAddress_Request.SerializeToString,
            addressValidation__pb2.ValidateAddress_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
